# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy.rb"
class Capy < Formula
  desc ""
  homepage ""
  version "1.0.27"
  depends_on :macos

  on_macos do
    url "https://identiq.jfrog.io/artifactory/homebrew/capy/1.0.27/capy_1.0.27_darwin.tar.gz", using: JfrogDownloadStrategy
    sha256 "178f6a867dc96aeaf4f587f980f8e20a1bcb0250940a153520ae96439fc8ba0c"

    def install
      bin.install "capy"
    end
  end
end
