# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy.rb"
class Capy < Formula
  desc ""
  homepage ""
  version "1.0.28"
  depends_on :macos

  on_macos do
    url "https://identiq.jfrog.io/artifactory/homebrew/capy/1.0.28/capy_1.0.28_darwin.tar.gz", using: JfrogDownloadStrategy
    sha256 "7c0949d11aaac4549467300fb1396bfc190ec176f10262e1c4ecb0091e7d0dc9"

    def install
      bin.install "capy"
    end
  end
end
