# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy.rb"
class Capy < Formula
  desc ""
  homepage ""
  version "1.0.21"
  depends_on :macos

  on_macos do
    url "https://identiq.jfrog.io/artifactory/homebrew/capy/1.0.21/capy_1.0.21_darwin.tar.gz", using: JfrogDownloadStrategy
    sha256 "776236e2dca124e2e193a4e2af8990e98f976427f45f03b70c0a2cac09401b5c"

    def install
      bin.install capy
    end
  end
end
