# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy.rb"
class Sesame < Formula
  desc ""
  homepage ""
  version "0.0.4"
  depends_on :macos

  on_macos do
    url "https://identiq.jfrog.io/artifactory/homebrew/sesame/0.0.4/ses_0.0.4_darwin.tar.gz", using: JfrogDownloadStrategy
    sha256 "cd28497525be6572fd3e7bff197779a9dbe615a90a28aa0ed97c1279bf4f06bf"

    def install
      bin.install "sesame" => "ses"
    end
  end
end
