# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy.rb"
class Sesame < Formula
  desc ""
  homepage ""
  version "0.0.6"
  depends_on :macos

  on_macos do
    url "https://identiq.jfrog.io/artifactory/homebrew/sesame/0.0.6/ses_0.0.6_darwin.tar.gz", using: JfrogDownloadStrategy
    sha256 "9ef380fdc95b03d9d1ca8be1e0fae51378e4f96c146db225024e0367c37003c4"

    def install
      bin.install "sesame" => "ses"
    end
  end
end
